### PR TITLE
App has been responsive for mobile device

### LINKED ISSUE #2: Add responsiveness for mobile
some things go out of bounds on mobile, and elements are too big at larger sizes

### PR DESCRIPTION
**Pull request by Shabbir-Building**
Check out the code please. The app is fit for mobile device now.

### CODE REVIEW

**Comment by ahmed-el-awad** [comment]
Thank you

**Comment by Shabbir-Building** [comment]
Welcome

**Comment by Shabbir-Building** [comment]
Are you web developer?

**Comment by ahmed-el-awad** [comment]
I am a computer science student currently learning web dev in my free time
Played around with some technologies but wouldn't say I am proficient

**Comment by Shabbir-Building** [comment]
Tha's great! most of the student do their productve works during graduation.

**Comment by Shabbir-Building** [comment]
Do you have account on linkedin?

**Comment by ahmed-el-awad** [comment]
Yeah I do
Feel free to send me yours if you want to connect

**Comment by Shabbir-Building** [comment]
Linkedin profile:
https://www.linkedin.com/in/amdadul-hoq-shabbir-185b7424a/

**Comment by Shabbir-Building** [comment]
Let's connect to get in touch.

**Pull request merged**
